"""Skill audit functionality for orchestrator readiness checks."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

import yaml


class AuditCheck(str, Enum):
    """Types of orchestrator readiness checks."""

    CHECKPOINT = "checkpoint"
    HEADLESS = "headless"
    CONTEXT_PATH = "context_path"
    ATTRIBUTION = "attribution"


@dataclass
class AuditResult:
    """Result of a single audit check."""

    passed: bool
    reason: str = ""
    auto_fixable: bool = False


@dataclass
class SkillAudit:
    """Audit results for a single skill."""

    name: str
    path: Path
    results: dict[AuditCheck, AuditResult] = field(default_factory=dict)

    @property
    def passed(self) -> bool:
        """True if all checks passed."""
        return all(r.passed for r in self.results.values())

    @property
    def status(self) -> str:
        """Human-readable status."""
        return "READY" if self.passed else "NOT READY"


@dataclass
class SkillInfo:
    """Basic skill information from SKILL.md."""

    name: str
    path: Path
    content: str
    frontmatter: dict


# Patterns for headless check
INTERACTIVE_PATTERNS = [
    r"\binput\s*\(",
    r"\bread\s+-p\b",
    r"Confirm\s*\(",
    r"typer\.confirm\s*\(",
]

BROWSER_ONLY_TOOLS = [
    "mcp__playwright__",
    "mcp__chrome_devtools__",
]

# Patterns for checkpoint check
CHECKPOINT_PATTERNS = [
    r"from\s+ctrlrelay\s+import\s+checkpoint",
    r"from\s+ctrlrelay\.core\.checkpoint\s+import",
    r"checkpoint\.(done|blocked|failed)\s*\(",
    r"CTRLRELAY_STATE_FILE",
]

# Attribution patterns to avoid in output
ATTRIBUTION_PATTERNS = [
    r"\bClaude\b",
    r"\bAnthropic\b",
    r"Generated by AI",
    r"AI Assistant",
]


def run_check(skill: SkillInfo, check: AuditCheck) -> AuditResult:
    """Run a single audit check on a skill."""
    content = skill.content
    tools = skill.frontmatter.get("tools", "")

    if check == AuditCheck.CHECKPOINT:
        for pattern in CHECKPOINT_PATTERNS:
            if re.search(pattern, content):
                return AuditResult(passed=True)
        return AuditResult(passed=False, reason="No checkpoint protocol usage found")

    if check == AuditCheck.HEADLESS:
        for pattern in INTERACTIVE_PATTERNS:
            if re.search(pattern, content):
                reason = f"Interactive prompt pattern found: {pattern}"
                return AuditResult(passed=False, reason=reason)
        for tool in BROWSER_ONLY_TOOLS:
            if tool in content or tool in tools:
                if "fallback" not in content.lower() and "cli" not in content.lower():
                    reason = f"Browser-only tool without fallback: {tool}"
                    return AuditResult(passed=False, reason=reason)
        return AuditResult(passed=True)

    if check == AuditCheck.CONTEXT_PATH:
        if "REPO_CONTEXT_PATH" in content or "$REPO_CONTEXT_PATH" in content:
            return AuditResult(passed=True)
        if "context" in content.lower() and "/" in content:
            return AuditResult(
                passed=False, reason="May use hardcoded context path", auto_fixable=True
            )
        return AuditResult(passed=True)

    if check == AuditCheck.ATTRIBUTION:
        for pattern in ATTRIBUTION_PATTERNS:
            match = re.search(pattern, content, re.IGNORECASE)
            if match:
                reason = f"Attribution pattern found: {match.group()}"
                return AuditResult(passed=False, reason=reason, auto_fixable=True)
        return AuditResult(passed=True)

    return AuditResult(passed=True)


def discover_skills(skills_dir: Path) -> list[SkillInfo]:
    """Discover all skills in a directory.

    Args:
        skills_dir: Path to skills directory.

    Returns:
        List of SkillInfo for each skill found.
    """
    skills = []

    if not skills_dir.exists():
        return skills

    for skill_md in skills_dir.glob("*/SKILL.md"):
        content = skill_md.read_text()

        # Parse YAML frontmatter
        frontmatter = {}
        match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
        if match:
            try:
                frontmatter = yaml.safe_load(match.group(1)) or {}
            except yaml.YAMLError:
                pass

        name = frontmatter.get("name", skill_md.parent.name)
        skills.append(
            SkillInfo(
                name=name,
                path=skill_md.parent,
                content=content,
                frontmatter=frontmatter,
            )
        )

    return sorted(skills, key=lambda s: s.name)


def audit_skill(skill: SkillInfo) -> SkillAudit:
    """Run all audit checks on a skill.

    Args:
        skill: Skill information.

    Returns:
        SkillAudit with all check results.
    """
    results = {}
    for check in AuditCheck:
        results[check] = run_check(skill, check)

    return SkillAudit(
        name=skill.name,
        path=skill.path,
        results=results,
    )


def audit_all(skills_dir: Path) -> list[SkillAudit]:
    """Audit all skills in a directory.

    Args:
        skills_dir: Path to skills directory.

    Returns:
        List of SkillAudit results.
    """
    skills = discover_skills(skills_dir)
    return [audit_skill(skill) for skill in skills]


def format_report(audits: list[SkillAudit]) -> str:
    """Format audit results as markdown report.

    Args:
        audits: List of skill audit results.

    Returns:
        Markdown formatted report.
    """
    lines = [
        "## Skill Audit Report",
        "",
        "| Skill | Checkpoint | Headless | Context | Attribution | Status |",
        "|-------|------------|----------|---------|-------------|--------|",
    ]

    for audit in audits:
        def icon(check: AuditCheck) -> str:
            result = audit.results.get(check)
            if result is None:
                return "➖"
            return "✅" if result.passed else "❌"

        lines.append(
            f"| {audit.name} "
            f"| {icon(AuditCheck.CHECKPOINT)} "
            f"| {icon(AuditCheck.HEADLESS)} "
            f"| {icon(AuditCheck.CONTEXT_PATH)} "
            f"| {icon(AuditCheck.ATTRIBUTION)} "
            f"| {audit.status} |"
        )

    # Summary
    ready = sum(1 for a in audits if a.passed)
    total = len(audits)
    lines.extend([
        "",
        f"**Summary:** {ready}/{total} skills ready for orchestrator",
    ])

    # Details for failed checks
    failed_audits = [a for a in audits if not a.passed]
    if failed_audits:
        lines.extend(["", "### Issues", ""])
        for audit in failed_audits:
            lines.append(f"**{audit.name}:**")
            for check, result in audit.results.items():
                if not result.passed:
                    fixable = " (auto-fixable)" if result.auto_fixable else ""
                    lines.append(f"- {check.value}: {result.reason}{fixable}")
            lines.append("")

    return "\n".join(lines)
