"""Skill audit functionality for orchestrator readiness checks."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

import yaml


class AuditCheck(str, Enum):
    """Types of orchestrator readiness checks."""

    CHECKPOINT = "checkpoint"
    HEADLESS = "headless"
    CONTEXT_PATH = "context_path"
    ATTRIBUTION = "attribution"


@dataclass
class AuditResult:
    """Result of a single audit check."""

    passed: bool
    reason: str = ""
    auto_fixable: bool = False


@dataclass
class SkillAudit:
    """Audit results for a single skill."""

    name: str
    path: Path
    results: dict[AuditCheck, AuditResult] = field(default_factory=dict)

    @property
    def passed(self) -> bool:
        """True if all checks passed."""
        return all(r.passed for r in self.results.values())

    @property
    def status(self) -> str:
        """Human-readable status."""
        return "READY" if self.passed else "NOT READY"


@dataclass
class SkillInfo:
    """Basic skill information from SKILL.md."""

    name: str
    path: Path
    content: str
    frontmatter: dict


# Patterns for headless check
INTERACTIVE_PATTERNS = [
    r"\binput\s*\(",
    r"\bread\s+-p\b",
    r"Confirm\s*\(",
    r"typer\.confirm\s*\(",
]

BROWSER_ONLY_TOOLS = [
    "mcp__playwright__",
    "mcp__chrome_devtools__",
]

# Patterns for checkpoint check
CHECKPOINT_PATTERNS = [
    r"from\s+dev_sync\s+import\s+checkpoint",
    r"from\s+dev_sync\.core\.checkpoint\s+import",
    r"checkpoint\.(done|blocked|failed)\s*\(",
    r"DEV_SYNC_STATE_FILE",
]

# Attribution patterns to avoid in output
ATTRIBUTION_PATTERNS = [
    r"\bClaude\b",
    r"\bAnthropic\b",
    r"Generated by AI",
    r"AI Assistant",
]


def run_check(skill: SkillInfo, check: AuditCheck) -> AuditResult:
    """Run a single audit check on a skill."""
    content = skill.content
    tools = skill.frontmatter.get("tools", "")

    if check == AuditCheck.CHECKPOINT:
        for pattern in CHECKPOINT_PATTERNS:
            if re.search(pattern, content):
                return AuditResult(passed=True)
        return AuditResult(passed=False, reason="No checkpoint protocol usage found")

    if check == AuditCheck.HEADLESS:
        for pattern in INTERACTIVE_PATTERNS:
            if re.search(pattern, content):
                return AuditResult(passed=False, reason=f"Interactive prompt pattern found: {pattern}")
        for tool in BROWSER_ONLY_TOOLS:
            if tool in content or tool in tools:
                if "fallback" not in content.lower() and "cli" not in content.lower():
                    return AuditResult(passed=False, reason=f"Browser-only tool without fallback: {tool}")
        return AuditResult(passed=True)

    if check == AuditCheck.CONTEXT_PATH:
        if "REPO_CONTEXT_PATH" in content or "$REPO_CONTEXT_PATH" in content:
            return AuditResult(passed=True)
        if "context" in content.lower() and "/" in content:
            return AuditResult(passed=False, reason="May use hardcoded context path", auto_fixable=True)
        return AuditResult(passed=True)

    if check == AuditCheck.ATTRIBUTION:
        for pattern in ATTRIBUTION_PATTERNS:
            match = re.search(pattern, content, re.IGNORECASE)
            if match:
                return AuditResult(passed=False, reason=f"Attribution pattern found: {match.group()}", auto_fixable=True)
        return AuditResult(passed=True)

    return AuditResult(passed=True)


def discover_skills(skills_dir: Path) -> list[SkillInfo]:
    """Discover all skills in a directory.

    Args:
        skills_dir: Path to skills directory.

    Returns:
        List of SkillInfo for each skill found.
    """
    skills = []

    if not skills_dir.exists():
        return skills

    for skill_md in skills_dir.glob("*/SKILL.md"):
        content = skill_md.read_text()

        # Parse YAML frontmatter
        frontmatter = {}
        match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
        if match:
            try:
                frontmatter = yaml.safe_load(match.group(1)) or {}
            except yaml.YAMLError:
                pass

        name = frontmatter.get("name", skill_md.parent.name)
        skills.append(
            SkillInfo(
                name=name,
                path=skill_md.parent,
                content=content,
                frontmatter=frontmatter,
            )
        )

    return sorted(skills, key=lambda s: s.name)


def audit_skill(skill: SkillInfo) -> SkillAudit:
    """Run all audit checks on a skill.

    Args:
        skill: Skill information.

    Returns:
        SkillAudit with all check results.
    """
    results = {}
    for check in AuditCheck:
        results[check] = run_check(skill, check)

    return SkillAudit(
        name=skill.name,
        path=skill.path,
        results=results,
    )


def audit_all(skills_dir: Path) -> list[SkillAudit]:
    """Audit all skills in a directory.

    Args:
        skills_dir: Path to skills directory.

    Returns:
        List of SkillAudit results.
    """
    skills = discover_skills(skills_dir)
    return [audit_skill(skill) for skill in skills]
